# -*- encoding: utf-8 -*-

=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "falaai-api/version"

Gem::Specification.new do |s|
  s.name        = "falaai-api"
  s.version     = FalaAI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Action Tec Br"]
  s.email       = ["livio@action.tec.br"]
  s.homepage    = "https://falaai.action.tec.br/api"
  s.summary     = "Official Ruby SDK for the FalaAI API"
  s.description = "Official Ruby SDK for the FalaAI API - AI-powered call transcription, diagnosis and compliance auditing."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {
    "homepage_uri"    => "https://falaai.action.tec.br/api",
    "source_code_uri" => "https://github.com/ActionTecBr/falaai-api-ruby",
    "bug_tracker_uri" => "https://github.com/ActionTecBr/falaai-api-ruby/issues",
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'mime-types', '~> 3.5'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir["lib/**/*", "docs/**/*", "LICENSE", "README.md"]
  s.require_paths = ["lib"]
end
