=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FalaAI::AnalysisApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalysisApi' do
  before do
    # run before each test
    @api_instance = FalaAI::AnalysisApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalysisApi' do
    it 'should create an instance of AnalysisApi' do
      expect(@api_instance).to be_instance_of(FalaAI::AnalysisApi)
    end
  end

  # unit tests for create_auditoria_risco_v1_analyze_auditoria_risco_post
  # Compliance Risk Audit — conversation compliance analysis
  # Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
  # @param auditoria_risco_request 
  # @param [Hash] opts the optional parameters
  # @return [AuditoriaRiscoV2Response]
  describe 'create_auditoria_risco_v1_analyze_auditoria_risco_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_diagnostic_v1_analyze_diagnostic_post
  # Analyze a call transcript — 5 parallel analyses
  # Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
  # @param diagnostic_request 
  # @param [Hash] opts the optional parameters
  # @return [DiagnosticResponse]
  describe 'create_diagnostic_v1_analyze_diagnostic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
