=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FalaAI::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = FalaAI::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(FalaAI::WebhooksApi)
    end
  end

  # unit tests for create_webhook_v1_webhooks_post
  # Criar webhook de alertas
  # Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
  # @param create_webhook_request 
  # @param [Hash] opts the optional parameters
  # @return [WebhookItem]
  describe 'create_webhook_v1_webhooks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_webhook_v1_webhooks_webhook_id_delete
  # Remover webhook
  # Remove inscricao de webhook por ID.
  # @param webhook_id 
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'delete_webhook_v1_webhooks_webhook_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_webhooks_v1_webhooks_get
  # Listar webhooks de alertas
  # Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Pagina (1-indexed)
  # @option opts [Integer] :limit Itens por pagina (max 100)
  # @return [WebhookListResponse]
  describe 'list_webhooks_v1_webhooks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_webhook_v1_webhooks_webhook_id_put
  # Atualizar webhook
  # Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
  # @param webhook_id 
  # @param update_webhook_request 
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'update_webhook_v1_webhooks_webhook_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
