=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class AuditoriaRiscoSummaryV2 < ApiModelBase
    # Total turns
    attr_accessor :total_turns

    # Total calibrated detections
    attr_accessor :total_calibrated

    # Active detections
    attr_accessor :active

    # Tolerated detections
    attr_accessor :tolerated

    # Blocked detections
    attr_accessor :blocked

    # Audio events used
    attr_accessor :audio_events_used

    # Audio events aggravated
    attr_accessor :audio_events_aggravated

    # MAC audio applied
    attr_accessor :mac_audio_applied

    # MVAD applied
    attr_accessor :mvad_applied

    # Total participants
    attr_accessor :total_participants

    # Total agents
    attr_accessor :total_agents

    # Total clients
    attr_accessor :total_clients

    # Total bots
    attr_accessor :total_bots

    # Total unknown
    attr_accessor :total_unknown

    # Client risk alerts count
    attr_accessor :client_risk_alerts_count

    # Client behavior alerts count
    attr_accessor :client_behavior_alerts_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'total_turns' => :'total_turns',
        :'total_calibrated' => :'total_calibrated',
        :'active' => :'active',
        :'tolerated' => :'tolerated',
        :'blocked' => :'blocked',
        :'audio_events_used' => :'audio_events_used',
        :'audio_events_aggravated' => :'audio_events_aggravated',
        :'mac_audio_applied' => :'mac_audio_applied',
        :'mvad_applied' => :'mvad_applied',
        :'total_participants' => :'total_participants',
        :'total_agents' => :'total_agents',
        :'total_clients' => :'total_clients',
        :'total_bots' => :'total_bots',
        :'total_unknown' => :'total_unknown',
        :'client_risk_alerts_count' => :'client_risk_alerts_count',
        :'client_behavior_alerts_count' => :'client_behavior_alerts_count'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'total_turns' => :'Integer',
        :'total_calibrated' => :'Integer',
        :'active' => :'Integer',
        :'tolerated' => :'Integer',
        :'blocked' => :'Integer',
        :'audio_events_used' => :'Integer',
        :'audio_events_aggravated' => :'Integer',
        :'mac_audio_applied' => :'Object',
        :'mvad_applied' => :'Object',
        :'total_participants' => :'Integer',
        :'total_agents' => :'Integer',
        :'total_clients' => :'Integer',
        :'total_bots' => :'Integer',
        :'total_unknown' => :'Integer',
        :'client_risk_alerts_count' => :'Integer',
        :'client_behavior_alerts_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'mac_audio_applied',
        :'mvad_applied',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::AuditoriaRiscoSummaryV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::AuditoriaRiscoSummaryV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'total_turns')
        self.total_turns = attributes[:'total_turns']
      end

      if attributes.key?(:'total_calibrated')
        self.total_calibrated = attributes[:'total_calibrated']
      end

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'tolerated')
        self.tolerated = attributes[:'tolerated']
      end

      if attributes.key?(:'blocked')
        self.blocked = attributes[:'blocked']
      end

      if attributes.key?(:'audio_events_used')
        self.audio_events_used = attributes[:'audio_events_used']
      end

      if attributes.key?(:'audio_events_aggravated')
        self.audio_events_aggravated = attributes[:'audio_events_aggravated']
      end

      if attributes.key?(:'mac_audio_applied')
        self.mac_audio_applied = attributes[:'mac_audio_applied']
      end

      if attributes.key?(:'mvad_applied')
        self.mvad_applied = attributes[:'mvad_applied']
      end

      if attributes.key?(:'total_participants')
        self.total_participants = attributes[:'total_participants']
      end

      if attributes.key?(:'total_agents')
        self.total_agents = attributes[:'total_agents']
      end

      if attributes.key?(:'total_clients')
        self.total_clients = attributes[:'total_clients']
      end

      if attributes.key?(:'total_bots')
        self.total_bots = attributes[:'total_bots']
      end

      if attributes.key?(:'total_unknown')
        self.total_unknown = attributes[:'total_unknown']
      end

      if attributes.key?(:'client_risk_alerts_count')
        self.client_risk_alerts_count = attributes[:'client_risk_alerts_count']
      end

      if attributes.key?(:'client_behavior_alerts_count')
        self.client_behavior_alerts_count = attributes[:'client_behavior_alerts_count']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          total_turns == o.total_turns &&
          total_calibrated == o.total_calibrated &&
          active == o.active &&
          tolerated == o.tolerated &&
          blocked == o.blocked &&
          audio_events_used == o.audio_events_used &&
          audio_events_aggravated == o.audio_events_aggravated &&
          mac_audio_applied == o.mac_audio_applied &&
          mvad_applied == o.mvad_applied &&
          total_participants == o.total_participants &&
          total_agents == o.total_agents &&
          total_clients == o.total_clients &&
          total_bots == o.total_bots &&
          total_unknown == o.total_unknown &&
          client_risk_alerts_count == o.client_risk_alerts_count &&
          client_behavior_alerts_count == o.client_behavior_alerts_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [total_turns, total_calibrated, active, tolerated, blocked, audio_events_used, audio_events_aggravated, mac_audio_applied, mvad_applied, total_participants, total_agents, total_clients, total_bots, total_unknown, client_risk_alerts_count, client_behavior_alerts_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
