=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  # Response V2 (build_public_response_v2) â€” blocos logicos EN-US. Fonte: response_builder.py.
  class AuditoriaRiscoV2 < ApiModelBase
    # Identification + usage
    attr_accessor :meta

    # Participants/roles/direction
    attr_accessor :participants

    # Verdict + level + applied actions
    attr_accessor :verdict

    # Consolidated + per-participant scores
    attr_accessor :scores

    # violations/positives/client alerts
    attr_accessor :detections

    # global_metrics + final_analysis + frameworks
    attr_accessor :analysis

    # turns_sentiment + audio_events + groups
    attr_accessor :timeline

    # MAC audio event semantics
    attr_accessor :audio_event_model

    # Per-category summary (keyed by category)
    attr_accessor :categories_summary

    # Suggested terms for bank
    attr_accessor :indexer

    # Executive summary counts
    attr_accessor :summary

    # Used actions i18n catalog (keyed by action)
    attr_accessor :acoes_i18n

    # Risk origin + validator changes
    attr_accessor :audit_decisions

    # Score composition explanation
    attr_accessor :scoring_explanation

    # HTML report (base64 gzip)
    attr_accessor :html_report

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'meta' => :'meta',
        :'participants' => :'participants',
        :'verdict' => :'verdict',
        :'scores' => :'scores',
        :'detections' => :'detections',
        :'analysis' => :'analysis',
        :'timeline' => :'timeline',
        :'audio_event_model' => :'audio_event_model',
        :'categories_summary' => :'categories_summary',
        :'indexer' => :'indexer',
        :'summary' => :'summary',
        :'acoes_i18n' => :'acoes_i18n',
        :'audit_decisions' => :'audit_decisions',
        :'scoring_explanation' => :'scoring_explanation',
        :'html_report' => :'html_report'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'meta' => :'AuditoriaRiscoMetaV2',
        :'participants' => :'AuditoriaRiscoParticipantsV2',
        :'verdict' => :'AuditoriaRiscoVerdictV2',
        :'scores' => :'AuditoriaRiscoScoresV2',
        :'detections' => :'AuditoriaRiscoDetectionsV2',
        :'analysis' => :'AuditoriaRiscoAnalysisV2',
        :'timeline' => :'AuditoriaRiscoTimelineV2',
        :'audio_event_model' => :'AuditoriaRiscoAudioEventModelV2',
        :'categories_summary' => :'Hash<String, Object>',
        :'indexer' => :'AuditoriaRiscoIndexerV2',
        :'summary' => :'AuditoriaRiscoSummaryV2',
        :'acoes_i18n' => :'Hash<String, Object>',
        :'audit_decisions' => :'AuditoriaRiscoAuditDecisionsV2',
        :'scoring_explanation' => :'AuditoriaRiscoScoringExplanationV2',
        :'html_report' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::AuditoriaRiscoV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::AuditoriaRiscoV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'meta')
        self.meta = attributes[:'meta']
      else
        self.meta = nil
      end

      if attributes.key?(:'participants')
        self.participants = attributes[:'participants']
      else
        self.participants = nil
      end

      if attributes.key?(:'verdict')
        self.verdict = attributes[:'verdict']
      else
        self.verdict = nil
      end

      if attributes.key?(:'scores')
        self.scores = attributes[:'scores']
      else
        self.scores = nil
      end

      if attributes.key?(:'detections')
        self.detections = attributes[:'detections']
      else
        self.detections = nil
      end

      if attributes.key?(:'analysis')
        self.analysis = attributes[:'analysis']
      else
        self.analysis = nil
      end

      if attributes.key?(:'timeline')
        self.timeline = attributes[:'timeline']
      else
        self.timeline = nil
      end

      if attributes.key?(:'audio_event_model')
        self.audio_event_model = attributes[:'audio_event_model']
      else
        self.audio_event_model = nil
      end

      if attributes.key?(:'categories_summary')
        if (value = attributes[:'categories_summary']).is_a?(Hash)
          self.categories_summary = value
        end
      else
        self.categories_summary = nil
      end

      if attributes.key?(:'indexer')
        self.indexer = attributes[:'indexer']
      else
        self.indexer = nil
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      else
        self.summary = nil
      end

      if attributes.key?(:'acoes_i18n')
        if (value = attributes[:'acoes_i18n']).is_a?(Hash)
          self.acoes_i18n = value
        end
      else
        self.acoes_i18n = nil
      end

      if attributes.key?(:'audit_decisions')
        self.audit_decisions = attributes[:'audit_decisions']
      else
        self.audit_decisions = nil
      end

      if attributes.key?(:'scoring_explanation')
        self.scoring_explanation = attributes[:'scoring_explanation']
      else
        self.scoring_explanation = nil
      end

      if attributes.key?(:'html_report')
        self.html_report = attributes[:'html_report']
      else
        self.html_report = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @meta.nil?
        invalid_properties.push('invalid value for "meta", meta cannot be nil.')
      end

      if @participants.nil?
        invalid_properties.push('invalid value for "participants", participants cannot be nil.')
      end

      if @verdict.nil?
        invalid_properties.push('invalid value for "verdict", verdict cannot be nil.')
      end

      if @scores.nil?
        invalid_properties.push('invalid value for "scores", scores cannot be nil.')
      end

      if @detections.nil?
        invalid_properties.push('invalid value for "detections", detections cannot be nil.')
      end

      if @analysis.nil?
        invalid_properties.push('invalid value for "analysis", analysis cannot be nil.')
      end

      if @timeline.nil?
        invalid_properties.push('invalid value for "timeline", timeline cannot be nil.')
      end

      if @audio_event_model.nil?
        invalid_properties.push('invalid value for "audio_event_model", audio_event_model cannot be nil.')
      end

      if @categories_summary.nil?
        invalid_properties.push('invalid value for "categories_summary", categories_summary cannot be nil.')
      end

      if @indexer.nil?
        invalid_properties.push('invalid value for "indexer", indexer cannot be nil.')
      end

      if @summary.nil?
        invalid_properties.push('invalid value for "summary", summary cannot be nil.')
      end

      if @acoes_i18n.nil?
        invalid_properties.push('invalid value for "acoes_i18n", acoes_i18n cannot be nil.')
      end

      if @audit_decisions.nil?
        invalid_properties.push('invalid value for "audit_decisions", audit_decisions cannot be nil.')
      end

      if @scoring_explanation.nil?
        invalid_properties.push('invalid value for "scoring_explanation", scoring_explanation cannot be nil.')
      end

      if @html_report.nil?
        invalid_properties.push('invalid value for "html_report", html_report cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @meta.nil?
      return false if @participants.nil?
      return false if @verdict.nil?
      return false if @scores.nil?
      return false if @detections.nil?
      return false if @analysis.nil?
      return false if @timeline.nil?
      return false if @audio_event_model.nil?
      return false if @categories_summary.nil?
      return false if @indexer.nil?
      return false if @summary.nil?
      return false if @acoes_i18n.nil?
      return false if @audit_decisions.nil?
      return false if @scoring_explanation.nil?
      return false if @html_report.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] meta Value to be assigned
    def meta=(meta)
      if meta.nil?
        fail ArgumentError, 'meta cannot be nil'
      end

      @meta = meta
    end

    # Custom attribute writer method with validation
    # @param [Object] participants Value to be assigned
    def participants=(participants)
      if participants.nil?
        fail ArgumentError, 'participants cannot be nil'
      end

      @participants = participants
    end

    # Custom attribute writer method with validation
    # @param [Object] verdict Value to be assigned
    def verdict=(verdict)
      if verdict.nil?
        fail ArgumentError, 'verdict cannot be nil'
      end

      @verdict = verdict
    end

    # Custom attribute writer method with validation
    # @param [Object] scores Value to be assigned
    def scores=(scores)
      if scores.nil?
        fail ArgumentError, 'scores cannot be nil'
      end

      @scores = scores
    end

    # Custom attribute writer method with validation
    # @param [Object] detections Value to be assigned
    def detections=(detections)
      if detections.nil?
        fail ArgumentError, 'detections cannot be nil'
      end

      @detections = detections
    end

    # Custom attribute writer method with validation
    # @param [Object] analysis Value to be assigned
    def analysis=(analysis)
      if analysis.nil?
        fail ArgumentError, 'analysis cannot be nil'
      end

      @analysis = analysis
    end

    # Custom attribute writer method with validation
    # @param [Object] timeline Value to be assigned
    def timeline=(timeline)
      if timeline.nil?
        fail ArgumentError, 'timeline cannot be nil'
      end

      @timeline = timeline
    end

    # Custom attribute writer method with validation
    # @param [Object] audio_event_model Value to be assigned
    def audio_event_model=(audio_event_model)
      if audio_event_model.nil?
        fail ArgumentError, 'audio_event_model cannot be nil'
      end

      @audio_event_model = audio_event_model
    end

    # Custom attribute writer method with validation
    # @param [Object] categories_summary Value to be assigned
    def categories_summary=(categories_summary)
      if categories_summary.nil?
        fail ArgumentError, 'categories_summary cannot be nil'
      end

      @categories_summary = categories_summary
    end

    # Custom attribute writer method with validation
    # @param [Object] indexer Value to be assigned
    def indexer=(indexer)
      if indexer.nil?
        fail ArgumentError, 'indexer cannot be nil'
      end

      @indexer = indexer
    end

    # Custom attribute writer method with validation
    # @param [Object] summary Value to be assigned
    def summary=(summary)
      if summary.nil?
        fail ArgumentError, 'summary cannot be nil'
      end

      @summary = summary
    end

    # Custom attribute writer method with validation
    # @param [Object] acoes_i18n Value to be assigned
    def acoes_i18n=(acoes_i18n)
      if acoes_i18n.nil?
        fail ArgumentError, 'acoes_i18n cannot be nil'
      end

      @acoes_i18n = acoes_i18n
    end

    # Custom attribute writer method with validation
    # @param [Object] audit_decisions Value to be assigned
    def audit_decisions=(audit_decisions)
      if audit_decisions.nil?
        fail ArgumentError, 'audit_decisions cannot be nil'
      end

      @audit_decisions = audit_decisions
    end

    # Custom attribute writer method with validation
    # @param [Object] scoring_explanation Value to be assigned
    def scoring_explanation=(scoring_explanation)
      if scoring_explanation.nil?
        fail ArgumentError, 'scoring_explanation cannot be nil'
      end

      @scoring_explanation = scoring_explanation
    end

    # Custom attribute writer method with validation
    # @param [Object] html_report Value to be assigned
    def html_report=(html_report)
      if html_report.nil?
        fail ArgumentError, 'html_report cannot be nil'
      end

      @html_report = html_report
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          meta == o.meta &&
          participants == o.participants &&
          verdict == o.verdict &&
          scores == o.scores &&
          detections == o.detections &&
          analysis == o.analysis &&
          timeline == o.timeline &&
          audio_event_model == o.audio_event_model &&
          categories_summary == o.categories_summary &&
          indexer == o.indexer &&
          summary == o.summary &&
          acoes_i18n == o.acoes_i18n &&
          audit_decisions == o.audit_decisions &&
          scoring_explanation == o.scoring_explanation &&
          html_report == o.html_report
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [meta, participants, verdict, scores, detections, analysis, timeline, audio_event_model, categories_summary, indexer, summary, acoes_i18n, audit_decisions, scoring_explanation, html_report].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
