=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class AuditoriaRiscoDetectionItemV2 < ApiModelBase
    # Turn number
    attr_accessor :turn

    # Speaker
    attr_accessor :interlocutor

    # Role
    attr_accessor :role

    # Start (s)
    attr_accessor :timestamp_start_s

    # End (s)
    attr_accessor :timestamp_end_s

    # Formatted timestamp
    attr_accessor :timestamp_formatted

    # Detected term
    attr_accessor :term_text

    # Suggested term for bank
    attr_accessor :suggested_term_for_bank

    # Category code
    attr_accessor :category

    # Category label (i18n)
    attr_accessor :category_label

    # Category color
    attr_accessor :category_color

    # Category icon
    attr_accessor :category_icon

    # Criticality
    attr_accessor :criticality

    # Category threshold
    attr_accessor :category_threshold

    # Category type
    attr_accessor :category_type

    # Category group label (i18n)
    attr_accessor :category_group

    # Nature
    attr_accessor :nature

    # LLM confidence
    attr_accessor :llm_confidence

    # Reason
    attr_accessor :reason

    # Valid context
    attr_accessor :is_valid_context

    # Risk probability
    attr_accessor :risk_probability

    # Risk impact
    attr_accessor :risk_impact

    # Category weight
    attr_accessor :category_weight

    # Turn sentiment
    attr_accessor :turn_sentiment

    # Intensity
    attr_accessor :intensity

    # Total modifier applied
    attr_accessor :mod_applied

    # Audio modifier applied
    attr_accessor :mac_applied

    # Intensity modifier applied
    attr_accessor :mvad_applied

    # Modifier formula
    attr_accessor :mod_formula

    # MAC details
    attr_accessor :mac_details

    # Calibration reason
    attr_accessor :calibration_reason

    # Final score
    attr_accessor :final_score

    # Final score formula
    attr_accessor :final_score_formula

    # Conversation limit
    attr_accessor :conversation_limit

    # Apply saturation
    attr_accessor :apply_saturation

    # Block repetition
    attr_accessor :block_repetition

    # Status
    attr_accessor :status

    # Effective impact
    attr_accessor :effective_impact

    # Saturation factor
    attr_accessor :saturation_factor

    # Saturation formula
    attr_accessor :saturation_formula

    # Threshold formula
    attr_accessor :threshold_formula

    # Blocked formula
    attr_accessor :blocked_formula

    # Reconciliation note
    attr_accessor :reconciliation_note

    # Violated frameworks
    attr_accessor :violated_frameworks

    # Citation fidelity
    attr_accessor :citation_fidelity

    # Subcategory code
    attr_accessor :subcategory

    # Subcategory label (i18n)
    attr_accessor :subcategory_label

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'turn' => :'turn',
        :'interlocutor' => :'interlocutor',
        :'role' => :'role',
        :'timestamp_start_s' => :'timestamp_start_s',
        :'timestamp_end_s' => :'timestamp_end_s',
        :'timestamp_formatted' => :'timestamp_formatted',
        :'term_text' => :'term_text',
        :'suggested_term_for_bank' => :'suggested_term_for_bank',
        :'category' => :'category',
        :'category_label' => :'category_label',
        :'category_color' => :'category_color',
        :'category_icon' => :'category_icon',
        :'criticality' => :'criticality',
        :'category_threshold' => :'category_threshold',
        :'category_type' => :'category_type',
        :'category_group' => :'category_group',
        :'nature' => :'nature',
        :'llm_confidence' => :'llm_confidence',
        :'reason' => :'reason',
        :'is_valid_context' => :'is_valid_context',
        :'risk_probability' => :'risk_probability',
        :'risk_impact' => :'risk_impact',
        :'category_weight' => :'category_weight',
        :'turn_sentiment' => :'turn_sentiment',
        :'intensity' => :'intensity',
        :'mod_applied' => :'mod_applied',
        :'mac_applied' => :'mac_applied',
        :'mvad_applied' => :'mvad_applied',
        :'mod_formula' => :'mod_formula',
        :'mac_details' => :'mac_details',
        :'calibration_reason' => :'calibration_reason',
        :'final_score' => :'final_score',
        :'final_score_formula' => :'final_score_formula',
        :'conversation_limit' => :'conversation_limit',
        :'apply_saturation' => :'apply_saturation',
        :'block_repetition' => :'block_repetition',
        :'status' => :'status',
        :'effective_impact' => :'effective_impact',
        :'saturation_factor' => :'saturation_factor',
        :'saturation_formula' => :'saturation_formula',
        :'threshold_formula' => :'threshold_formula',
        :'blocked_formula' => :'blocked_formula',
        :'reconciliation_note' => :'reconciliation_note',
        :'violated_frameworks' => :'violated_frameworks',
        :'citation_fidelity' => :'citation_fidelity',
        :'subcategory' => :'subcategory',
        :'subcategory_label' => :'subcategory_label'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'turn' => :'Integer',
        :'interlocutor' => :'String',
        :'role' => :'String',
        :'timestamp_start_s' => :'Float',
        :'timestamp_end_s' => :'Float',
        :'timestamp_formatted' => :'String',
        :'term_text' => :'String',
        :'suggested_term_for_bank' => :'Object',
        :'category' => :'String',
        :'category_label' => :'String',
        :'category_color' => :'String',
        :'category_icon' => :'String',
        :'criticality' => :'String',
        :'category_threshold' => :'Float',
        :'category_type' => :'String',
        :'category_group' => :'String',
        :'nature' => :'String',
        :'llm_confidence' => :'Float',
        :'reason' => :'String',
        :'is_valid_context' => :'Boolean',
        :'risk_probability' => :'Float',
        :'risk_impact' => :'Float',
        :'category_weight' => :'Float',
        :'turn_sentiment' => :'String',
        :'intensity' => :'Object',
        :'mod_applied' => :'Float',
        :'mac_applied' => :'Float',
        :'mvad_applied' => :'Float',
        :'mod_formula' => :'String',
        :'mac_details' => :'Array<Hash<String, Object>>',
        :'calibration_reason' => :'String',
        :'final_score' => :'Float',
        :'final_score_formula' => :'String',
        :'conversation_limit' => :'Object',
        :'apply_saturation' => :'Boolean',
        :'block_repetition' => :'Boolean',
        :'status' => :'String',
        :'effective_impact' => :'Float',
        :'saturation_factor' => :'Float',
        :'saturation_formula' => :'String',
        :'threshold_formula' => :'String',
        :'blocked_formula' => :'String',
        :'reconciliation_note' => :'String',
        :'violated_frameworks' => :'Array<Object>',
        :'citation_fidelity' => :'Boolean',
        :'subcategory' => :'String',
        :'subcategory_label' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'suggested_term_for_bank',
        :'intensity',
        :'conversation_limit',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::AuditoriaRiscoDetectionItemV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::AuditoriaRiscoDetectionItemV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'turn')
        self.turn = attributes[:'turn']
      end

      if attributes.key?(:'interlocutor')
        self.interlocutor = attributes[:'interlocutor']
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      end

      if attributes.key?(:'timestamp_start_s')
        self.timestamp_start_s = attributes[:'timestamp_start_s']
      end

      if attributes.key?(:'timestamp_end_s')
        self.timestamp_end_s = attributes[:'timestamp_end_s']
      end

      if attributes.key?(:'timestamp_formatted')
        self.timestamp_formatted = attributes[:'timestamp_formatted']
      end

      if attributes.key?(:'term_text')
        self.term_text = attributes[:'term_text']
      end

      if attributes.key?(:'suggested_term_for_bank')
        self.suggested_term_for_bank = attributes[:'suggested_term_for_bank']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'category_label')
        self.category_label = attributes[:'category_label']
      else
        self.category_label = nil
      end

      if attributes.key?(:'category_color')
        self.category_color = attributes[:'category_color']
      end

      if attributes.key?(:'category_icon')
        self.category_icon = attributes[:'category_icon']
      end

      if attributes.key?(:'criticality')
        self.criticality = attributes[:'criticality']
      end

      if attributes.key?(:'category_threshold')
        self.category_threshold = attributes[:'category_threshold']
      end

      if attributes.key?(:'category_type')
        self.category_type = attributes[:'category_type']
      end

      if attributes.key?(:'category_group')
        self.category_group = attributes[:'category_group']
      else
        self.category_group = nil
      end

      if attributes.key?(:'nature')
        self.nature = attributes[:'nature']
      end

      if attributes.key?(:'llm_confidence')
        self.llm_confidence = attributes[:'llm_confidence']
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end

      if attributes.key?(:'is_valid_context')
        self.is_valid_context = attributes[:'is_valid_context']
      end

      if attributes.key?(:'risk_probability')
        self.risk_probability = attributes[:'risk_probability']
      end

      if attributes.key?(:'risk_impact')
        self.risk_impact = attributes[:'risk_impact']
      end

      if attributes.key?(:'category_weight')
        self.category_weight = attributes[:'category_weight']
      end

      if attributes.key?(:'turn_sentiment')
        self.turn_sentiment = attributes[:'turn_sentiment']
      end

      if attributes.key?(:'intensity')
        self.intensity = attributes[:'intensity']
      end

      if attributes.key?(:'mod_applied')
        self.mod_applied = attributes[:'mod_applied']
      end

      if attributes.key?(:'mac_applied')
        self.mac_applied = attributes[:'mac_applied']
      end

      if attributes.key?(:'mvad_applied')
        self.mvad_applied = attributes[:'mvad_applied']
      end

      if attributes.key?(:'mod_formula')
        self.mod_formula = attributes[:'mod_formula']
      end

      if attributes.key?(:'mac_details')
        if (value = attributes[:'mac_details']).is_a?(Array)
          self.mac_details = value
        end
      end

      if attributes.key?(:'calibration_reason')
        self.calibration_reason = attributes[:'calibration_reason']
      end

      if attributes.key?(:'final_score')
        self.final_score = attributes[:'final_score']
      end

      if attributes.key?(:'final_score_formula')
        self.final_score_formula = attributes[:'final_score_formula']
      end

      if attributes.key?(:'conversation_limit')
        self.conversation_limit = attributes[:'conversation_limit']
      end

      if attributes.key?(:'apply_saturation')
        self.apply_saturation = attributes[:'apply_saturation']
      end

      if attributes.key?(:'block_repetition')
        self.block_repetition = attributes[:'block_repetition']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'effective_impact')
        self.effective_impact = attributes[:'effective_impact']
      end

      if attributes.key?(:'saturation_factor')
        self.saturation_factor = attributes[:'saturation_factor']
      end

      if attributes.key?(:'saturation_formula')
        self.saturation_formula = attributes[:'saturation_formula']
      end

      if attributes.key?(:'threshold_formula')
        self.threshold_formula = attributes[:'threshold_formula']
      end

      if attributes.key?(:'blocked_formula')
        self.blocked_formula = attributes[:'blocked_formula']
      end

      if attributes.key?(:'reconciliation_note')
        self.reconciliation_note = attributes[:'reconciliation_note']
      end

      if attributes.key?(:'violated_frameworks')
        if (value = attributes[:'violated_frameworks']).is_a?(Array)
          self.violated_frameworks = value
        end
      end

      if attributes.key?(:'citation_fidelity')
        self.citation_fidelity = attributes[:'citation_fidelity']
      else
        self.citation_fidelity = true
      end

      if attributes.key?(:'subcategory')
        self.subcategory = attributes[:'subcategory']
      end

      if attributes.key?(:'subcategory_label')
        self.subcategory_label = attributes[:'subcategory_label']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @category_label.nil?
        invalid_properties.push('invalid value for "category_label", category_label cannot be nil.')
      end

      if @category_group.nil?
        invalid_properties.push('invalid value for "category_group", category_group cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @category_label.nil?
      return false if @category_group.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] category_label Value to be assigned
    def category_label=(category_label)
      if category_label.nil?
        fail ArgumentError, 'category_label cannot be nil'
      end

      @category_label = category_label
    end

    # Custom attribute writer method with validation
    # @param [Object] category_group Value to be assigned
    def category_group=(category_group)
      if category_group.nil?
        fail ArgumentError, 'category_group cannot be nil'
      end

      @category_group = category_group
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          turn == o.turn &&
          interlocutor == o.interlocutor &&
          role == o.role &&
          timestamp_start_s == o.timestamp_start_s &&
          timestamp_end_s == o.timestamp_end_s &&
          timestamp_formatted == o.timestamp_formatted &&
          term_text == o.term_text &&
          suggested_term_for_bank == o.suggested_term_for_bank &&
          category == o.category &&
          category_label == o.category_label &&
          category_color == o.category_color &&
          category_icon == o.category_icon &&
          criticality == o.criticality &&
          category_threshold == o.category_threshold &&
          category_type == o.category_type &&
          category_group == o.category_group &&
          nature == o.nature &&
          llm_confidence == o.llm_confidence &&
          reason == o.reason &&
          is_valid_context == o.is_valid_context &&
          risk_probability == o.risk_probability &&
          risk_impact == o.risk_impact &&
          category_weight == o.category_weight &&
          turn_sentiment == o.turn_sentiment &&
          intensity == o.intensity &&
          mod_applied == o.mod_applied &&
          mac_applied == o.mac_applied &&
          mvad_applied == o.mvad_applied &&
          mod_formula == o.mod_formula &&
          mac_details == o.mac_details &&
          calibration_reason == o.calibration_reason &&
          final_score == o.final_score &&
          final_score_formula == o.final_score_formula &&
          conversation_limit == o.conversation_limit &&
          apply_saturation == o.apply_saturation &&
          block_repetition == o.block_repetition &&
          status == o.status &&
          effective_impact == o.effective_impact &&
          saturation_factor == o.saturation_factor &&
          saturation_formula == o.saturation_formula &&
          threshold_formula == o.threshold_formula &&
          blocked_formula == o.blocked_formula &&
          reconciliation_note == o.reconciliation_note &&
          violated_frameworks == o.violated_frameworks &&
          citation_fidelity == o.citation_fidelity &&
          subcategory == o.subcategory &&
          subcategory_label == o.subcategory_label
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [turn, interlocutor, role, timestamp_start_s, timestamp_end_s, timestamp_formatted, term_text, suggested_term_for_bank, category, category_label, category_color, category_icon, criticality, category_threshold, category_type, category_group, nature, llm_confidence, reason, is_valid_context, risk_probability, risk_impact, category_weight, turn_sentiment, intensity, mod_applied, mac_applied, mvad_applied, mod_formula, mac_details, calibration_reason, final_score, final_score_formula, conversation_limit, apply_saturation, block_repetition, status, effective_impact, saturation_factor, saturation_formula, threshold_formula, blocked_formula, reconciliation_note, violated_frameworks, citation_fidelity, subcategory, subcategory_label].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
