=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class AuditoriaRiscoRequest < ApiModelBase
    # Analysis model. Always 'falaai-auditoria-risco-1'
    attr_accessor :model

    # Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
    attr_accessor :text

    # Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
    attr_accessor :dialog

    # Audio events with timestamps (correlated with turns when diarization is present)
    attr_accessor :audio_events

    # Total audio duration in seconds. Required. Max 3h (10800s).
    attr_accessor :duration_seconds

    # Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
    attr_accessor :language

    # Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from 'language'. Accepted: pt-BR, en-US, es-ES.
    attr_accessor :response_language

    # Who originated the call. inbound=client called, outbound=company called. If omitted, LLM infers from context.
    attr_accessor :call_direction

    # Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth â€” no inference.
    attr_accessor :participants

    # Response format version. v1=legacy flat PT-BR, v2=structured EN-US blocks.
    attr_accessor :response_format

    # Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
    attr_accessor :client_reference_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'model' => :'model',
        :'text' => :'text',
        :'dialog' => :'dialog',
        :'audio_events' => :'audio_events',
        :'duration_seconds' => :'duration_seconds',
        :'language' => :'language',
        :'response_language' => :'response_language',
        :'call_direction' => :'call_direction',
        :'participants' => :'participants',
        :'response_format' => :'response_format',
        :'client_reference_id' => :'client_reference_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'model' => :'String',
        :'text' => :'String',
        :'dialog' => :'String',
        :'audio_events' => :'Array<DiagnosticAudioEvent>',
        :'duration_seconds' => :'Float',
        :'language' => :'String',
        :'response_language' => :'String',
        :'call_direction' => :'String',
        :'participants' => :'Array<Participant>',
        :'response_format' => :'String',
        :'client_reference_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::AuditoriaRiscoRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::AuditoriaRiscoRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = 'falaai-auditoria-risco-1'
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      else
        self.text = ''
      end

      if attributes.key?(:'dialog')
        self.dialog = attributes[:'dialog']
      else
        self.dialog = ''
      end

      if attributes.key?(:'audio_events')
        if (value = attributes[:'audio_events']).is_a?(Array)
          self.audio_events = value
        end
      end

      if attributes.key?(:'duration_seconds')
        self.duration_seconds = attributes[:'duration_seconds']
      else
        self.duration_seconds = nil
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      else
        self.language = nil
      end

      if attributes.key?(:'response_language')
        self.response_language = attributes[:'response_language']
      else
        self.response_language = nil
      end

      if attributes.key?(:'call_direction')
        self.call_direction = attributes[:'call_direction']
      end

      if attributes.key?(:'participants')
        if (value = attributes[:'participants']).is_a?(Array)
          self.participants = value
        end
      end

      if attributes.key?(:'response_format')
        self.response_format = attributes[:'response_format']
      else
        self.response_format = 'v2'
      end

      if attributes.key?(:'client_reference_id')
        self.client_reference_id = attributes[:'client_reference_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@text.nil? && @text.to_s.length > 300000
        invalid_properties.push('invalid value for "text", the character length must be smaller than or equal to 300000.')
      end

      if !@dialog.nil? && @dialog.to_s.length > 300000
        invalid_properties.push('invalid value for "dialog", the character length must be smaller than or equal to 300000.')
      end

      if !@audio_events.nil? && @audio_events.length > 500
        invalid_properties.push('invalid value for "audio_events", number of items must be less than or equal to 500.')
      end

      if @duration_seconds.nil?
        invalid_properties.push('invalid value for "duration_seconds", duration_seconds cannot be nil.')
      end

      if @duration_seconds < 1.0
        invalid_properties.push('invalid value for "duration_seconds", must be greater than or equal to 1.0.')
      end

      if @language.nil?
        invalid_properties.push('invalid value for "language", language cannot be nil.')
      end

      if @response_language.nil?
        invalid_properties.push('invalid value for "response_language", response_language cannot be nil.')
      end

      if !@participants.nil? && @participants.length > 10
        invalid_properties.push('invalid value for "participants", number of items must be less than or equal to 10.')
      end

      pattern = Regexp.new(/^v[0-9]+$/)
      if !@response_format.nil? && @response_format !~ pattern
        invalid_properties.push("invalid value for \"response_format\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@text.nil? && @text.to_s.length > 300000
      return false if !@dialog.nil? && @dialog.to_s.length > 300000
      return false if !@audio_events.nil? && @audio_events.length > 500
      return false if @duration_seconds.nil?
      return false if @duration_seconds < 1.0
      return false if @language.nil?
      return false if @response_language.nil?
      call_direction_validator = EnumAttributeValidator.new('String', ["inbound", "outbound"])
      return false unless call_direction_validator.valid?(@call_direction)
      return false if !@participants.nil? && @participants.length > 10
      return false if !@response_format.nil? && @response_format !~ Regexp.new(/^v[0-9]+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if text.nil?
        fail ArgumentError, 'text cannot be nil'
      end

      if text.to_s.length > 300000
        fail ArgumentError, 'invalid value for "text", the character length must be smaller than or equal to 300000.'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] dialog Value to be assigned
    def dialog=(dialog)
      if dialog.nil?
        fail ArgumentError, 'dialog cannot be nil'
      end

      if dialog.to_s.length > 300000
        fail ArgumentError, 'invalid value for "dialog", the character length must be smaller than or equal to 300000.'
      end

      @dialog = dialog
    end

    # Custom attribute writer method with validation
    # @param [Object] audio_events Value to be assigned
    def audio_events=(audio_events)
      if audio_events.nil?
        fail ArgumentError, 'audio_events cannot be nil'
      end

      if audio_events.length > 500
        fail ArgumentError, 'invalid value for "audio_events", number of items must be less than or equal to 500.'
      end

      @audio_events = audio_events
    end

    # Custom attribute writer method with validation
    # @param [Object] duration_seconds Value to be assigned
    def duration_seconds=(duration_seconds)
      if duration_seconds.nil?
        fail ArgumentError, 'duration_seconds cannot be nil'
      end

      if duration_seconds < 1.0
        fail ArgumentError, 'invalid value for "duration_seconds", must be greater than or equal to 1.0.'
      end

      @duration_seconds = duration_seconds
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] response_language Value to be assigned
    def response_language=(response_language)
      if response_language.nil?
        fail ArgumentError, 'response_language cannot be nil'
      end

      @response_language = response_language
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] call_direction Object to be assigned
    def call_direction=(call_direction)
      validator = EnumAttributeValidator.new('String', ["inbound", "outbound"])
      unless validator.valid?(call_direction)
        fail ArgumentError, "invalid value for \"call_direction\", must be one of #{validator.allowable_values}."
      end
      @call_direction = call_direction
    end

    # Custom attribute writer method with validation
    # @param [Object] participants Value to be assigned
    def participants=(participants)
      if participants.nil?
        fail ArgumentError, 'participants cannot be nil'
      end

      if participants.length > 10
        fail ArgumentError, 'invalid value for "participants", number of items must be less than or equal to 10.'
      end

      @participants = participants
    end

    # Custom attribute writer method with validation
    # @param [Object] response_format Value to be assigned
    def response_format=(response_format)
      if response_format.nil?
        fail ArgumentError, 'response_format cannot be nil'
      end

      pattern = Regexp.new(/^v[0-9]+$/)
      if response_format !~ pattern
        fail ArgumentError, "invalid value for \"response_format\", must conform to the pattern #{pattern}."
      end

      @response_format = response_format
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          model == o.model &&
          text == o.text &&
          dialog == o.dialog &&
          audio_events == o.audio_events &&
          duration_seconds == o.duration_seconds &&
          language == o.language &&
          response_language == o.response_language &&
          call_direction == o.call_direction &&
          participants == o.participants &&
          response_format == o.response_format &&
          client_reference_id == o.client_reference_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [model, text, dialog, audio_events, duration_seconds, language, response_language, call_direction, participants, response_format, client_reference_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
