=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class AudioInputMeta < ApiModelBase
    # Exact audio duration sent in seconds
    attr_accessor :duration_s

    # Original file format (wav, mp3, ogg, etc)
    attr_accessor :original_format

    # Audio codec sent
    attr_accessor :codec

    # Audio sample rate in Hz
    attr_accessor :sample_rate

    # Number of channels (1=mono, 2=stereo)
    attr_accessor :channels

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'duration_s' => :'duration_s',
        :'original_format' => :'original_format',
        :'codec' => :'codec',
        :'sample_rate' => :'sample_rate',
        :'channels' => :'channels'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'duration_s' => :'Float',
        :'original_format' => :'String',
        :'codec' => :'String',
        :'sample_rate' => :'Integer',
        :'channels' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::AudioInputMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::AudioInputMeta`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'duration_s')
        self.duration_s = attributes[:'duration_s']
      else
        self.duration_s = nil
      end

      if attributes.key?(:'original_format')
        self.original_format = attributes[:'original_format']
      else
        self.original_format = nil
      end

      if attributes.key?(:'codec')
        self.codec = attributes[:'codec']
      else
        self.codec = nil
      end

      if attributes.key?(:'sample_rate')
        self.sample_rate = attributes[:'sample_rate']
      else
        self.sample_rate = nil
      end

      if attributes.key?(:'channels')
        self.channels = attributes[:'channels']
      else
        self.channels = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @duration_s.nil?
        invalid_properties.push('invalid value for "duration_s", duration_s cannot be nil.')
      end

      if @original_format.nil?
        invalid_properties.push('invalid value for "original_format", original_format cannot be nil.')
      end

      if @codec.nil?
        invalid_properties.push('invalid value for "codec", codec cannot be nil.')
      end

      if @sample_rate.nil?
        invalid_properties.push('invalid value for "sample_rate", sample_rate cannot be nil.')
      end

      if @channels.nil?
        invalid_properties.push('invalid value for "channels", channels cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @duration_s.nil?
      return false if @original_format.nil?
      return false if @codec.nil?
      return false if @sample_rate.nil?
      return false if @channels.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] duration_s Value to be assigned
    def duration_s=(duration_s)
      if duration_s.nil?
        fail ArgumentError, 'duration_s cannot be nil'
      end

      @duration_s = duration_s
    end

    # Custom attribute writer method with validation
    # @param [Object] original_format Value to be assigned
    def original_format=(original_format)
      if original_format.nil?
        fail ArgumentError, 'original_format cannot be nil'
      end

      @original_format = original_format
    end

    # Custom attribute writer method with validation
    # @param [Object] codec Value to be assigned
    def codec=(codec)
      if codec.nil?
        fail ArgumentError, 'codec cannot be nil'
      end

      @codec = codec
    end

    # Custom attribute writer method with validation
    # @param [Object] sample_rate Value to be assigned
    def sample_rate=(sample_rate)
      if sample_rate.nil?
        fail ArgumentError, 'sample_rate cannot be nil'
      end

      @sample_rate = sample_rate
    end

    # Custom attribute writer method with validation
    # @param [Object] channels Value to be assigned
    def channels=(channels)
      if channels.nil?
        fail ArgumentError, 'channels cannot be nil'
      end

      @channels = channels
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          duration_s == o.duration_s &&
          original_format == o.original_format &&
          codec == o.codec &&
          sample_rate == o.sample_rate &&
          channels == o.channels
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [duration_s, original_format, codec, sample_rate, channels].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
