=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class DiagnosticAnalysisMap < ApiModelBase
    # Detailed conversation summary
    attr_accessor :dialogue_summary

    # Initial contact reason
    attr_accessor :contact_reason

    # Action taken / resolution
    attr_accessor :identified_action

    # Theme classification
    attr_accessor :identified_label

    # Predominant sentiment
    attr_accessor :sentiment

    # Identified participants and roles (same field names as auditoria)
    attr_accessor :participants_identified

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'dialogue_summary' => :'dialogue_summary',
        :'contact_reason' => :'contact_reason',
        :'identified_action' => :'identified_action',
        :'identified_label' => :'identified_label',
        :'sentiment' => :'sentiment',
        :'participants_identified' => :'participants_identified'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'dialogue_summary' => :'DiagnosticTextAnalysis',
        :'contact_reason' => :'DiagnosticTextAnalysis',
        :'identified_action' => :'DiagnosticCategoricalAnalysis',
        :'identified_label' => :'DiagnosticCategoricalAnalysis',
        :'sentiment' => :'DiagnosticCategoricalAnalysis',
        :'participants_identified' => :'Array<ParticipantDiagnostic>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::DiagnosticAnalysisMap` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::DiagnosticAnalysisMap`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'dialogue_summary')
        self.dialogue_summary = attributes[:'dialogue_summary']
      else
        self.dialogue_summary = nil
      end

      if attributes.key?(:'contact_reason')
        self.contact_reason = attributes[:'contact_reason']
      else
        self.contact_reason = nil
      end

      if attributes.key?(:'identified_action')
        self.identified_action = attributes[:'identified_action']
      else
        self.identified_action = nil
      end

      if attributes.key?(:'identified_label')
        self.identified_label = attributes[:'identified_label']
      else
        self.identified_label = nil
      end

      if attributes.key?(:'sentiment')
        self.sentiment = attributes[:'sentiment']
      else
        self.sentiment = nil
      end

      if attributes.key?(:'participants_identified')
        if (value = attributes[:'participants_identified']).is_a?(Array)
          self.participants_identified = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @dialogue_summary.nil?
        invalid_properties.push('invalid value for "dialogue_summary", dialogue_summary cannot be nil.')
      end

      if @contact_reason.nil?
        invalid_properties.push('invalid value for "contact_reason", contact_reason cannot be nil.')
      end

      if @identified_action.nil?
        invalid_properties.push('invalid value for "identified_action", identified_action cannot be nil.')
      end

      if @identified_label.nil?
        invalid_properties.push('invalid value for "identified_label", identified_label cannot be nil.')
      end

      if @sentiment.nil?
        invalid_properties.push('invalid value for "sentiment", sentiment cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @dialogue_summary.nil?
      return false if @contact_reason.nil?
      return false if @identified_action.nil?
      return false if @identified_label.nil?
      return false if @sentiment.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] dialogue_summary Value to be assigned
    def dialogue_summary=(dialogue_summary)
      if dialogue_summary.nil?
        fail ArgumentError, 'dialogue_summary cannot be nil'
      end

      @dialogue_summary = dialogue_summary
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_reason Value to be assigned
    def contact_reason=(contact_reason)
      if contact_reason.nil?
        fail ArgumentError, 'contact_reason cannot be nil'
      end

      @contact_reason = contact_reason
    end

    # Custom attribute writer method with validation
    # @param [Object] identified_action Value to be assigned
    def identified_action=(identified_action)
      if identified_action.nil?
        fail ArgumentError, 'identified_action cannot be nil'
      end

      @identified_action = identified_action
    end

    # Custom attribute writer method with validation
    # @param [Object] identified_label Value to be assigned
    def identified_label=(identified_label)
      if identified_label.nil?
        fail ArgumentError, 'identified_label cannot be nil'
      end

      @identified_label = identified_label
    end

    # Custom attribute writer method with validation
    # @param [Object] sentiment Value to be assigned
    def sentiment=(sentiment)
      if sentiment.nil?
        fail ArgumentError, 'sentiment cannot be nil'
      end

      @sentiment = sentiment
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          dialogue_summary == o.dialogue_summary &&
          contact_reason == o.contact_reason &&
          identified_action == o.identified_action &&
          identified_label == o.identified_label &&
          sentiment == o.sentiment &&
          participants_identified == o.participants_identified
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [dialogue_summary, contact_reason, identified_action, identified_label, sentiment, participants_identified].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
