=begin
#FalaAI API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.49

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class EmailEvent
    SUBSCRIPTION_CREATED = "subscription.created".freeze
    AVULSO_COMPLETED = "avulso.completed".freeze
    SUBSCRIPTION_UPGRADED = "subscription.upgraded".freeze
    SUBSCRIPTION_DOWNGRADED = "subscription.downgraded".freeze
    SUBSCRIPTION_CANCELED = "subscription.canceled".freeze
    CREDITS_LOW = "credits.low".freeze
    CREDITS_EXHAUSTED = "credits.exhausted".freeze
    SUBSCRIPTION_RENEWED = "subscription.renewed".freeze
    PAYMENT_FAILED = "payment.failed".freeze

    def self.all_vars
      @all_vars ||= [SUBSCRIPTION_CREATED, AVULSO_COMPLETED, SUBSCRIPTION_UPGRADED, SUBSCRIPTION_DOWNGRADED, SUBSCRIPTION_CANCELED, CREDITS_LOW, CREDITS_EXHAUSTED, SUBSCRIPTION_RENEWED, PAYMENT_FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EmailEvent.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EmailEvent"
    end
  end
end
