=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class TranscriptionResponse < ApiModelBase
    # Unique transcription identifier. Prefix 'tr-' followed by UUID
    attr_accessor :id

    # Returned object type. Always 'transcription'
    attr_accessor :object

    # Model used for transcription. Ex: 'falaai-transcribe-1'
    attr_accessor :model

    # Original audio file name uploaded
    attr_accessor :filename

    # Processing datetime in ISO 8601 UTC format
    attr_accessor :processed_at

    # Usage and processing information
    attr_accessor :usage

    # ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)
    attr_accessor :language

    # Language detection confidence level (0.0 to 1.0). Higher is more reliable
    attr_accessor :language_confidence

    # Total audio duration in seconds
    attr_accessor :duration_seconds

    # Full transcription as plain text, including audio events in brackets
    attr_accessor :text

    # Turn-by-turn formatted transcript with speaker identification and start/end timestamps
    attr_accessor :dialog

    # List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration
    attr_accessor :audio_events

    # Unique audio event types found in transcription, alphabetically sorted
    attr_accessor :event_types

    # Total number of recognized words in transcription
    attr_accessor :word_count

    # Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais)
    attr_accessor :input

    # Client-supplied ID echoed verbatim (if provided in request)
    attr_accessor :client_reference_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object' => :'object',
        :'model' => :'model',
        :'filename' => :'filename',
        :'processed_at' => :'processed_at',
        :'usage' => :'usage',
        :'language' => :'language',
        :'language_confidence' => :'language_confidence',
        :'duration_seconds' => :'duration_seconds',
        :'text' => :'text',
        :'dialog' => :'dialog',
        :'audio_events' => :'audio_events',
        :'event_types' => :'event_types',
        :'word_count' => :'word_count',
        :'input' => :'input',
        :'client_reference_id' => :'client_reference_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'object' => :'String',
        :'model' => :'String',
        :'filename' => :'String',
        :'processed_at' => :'String',
        :'usage' => :'TranscriptionUsage',
        :'language' => :'String',
        :'language_confidence' => :'Float',
        :'duration_seconds' => :'Float',
        :'text' => :'String',
        :'dialog' => :'String',
        :'audio_events' => :'Array<AudioEvent>',
        :'event_types' => :'Array<String>',
        :'word_count' => :'Integer',
        :'input' => :'AudioInputMeta',
        :'client_reference_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::TranscriptionResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::TranscriptionResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = nil
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      else
        self.filename = nil
      end

      if attributes.key?(:'processed_at')
        self.processed_at = attributes[:'processed_at']
      else
        self.processed_at = nil
      end

      if attributes.key?(:'usage')
        self.usage = attributes[:'usage']
      else
        self.usage = nil
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      else
        self.language = nil
      end

      if attributes.key?(:'language_confidence')
        self.language_confidence = attributes[:'language_confidence']
      end

      if attributes.key?(:'duration_seconds')
        self.duration_seconds = attributes[:'duration_seconds']
      else
        self.duration_seconds = nil
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      else
        self.text = nil
      end

      if attributes.key?(:'dialog')
        self.dialog = attributes[:'dialog']
      else
        self.dialog = nil
      end

      if attributes.key?(:'audio_events')
        if (value = attributes[:'audio_events']).is_a?(Array)
          self.audio_events = value
        end
      else
        self.audio_events = nil
      end

      if attributes.key?(:'event_types')
        if (value = attributes[:'event_types']).is_a?(Array)
          self.event_types = value
        end
      else
        self.event_types = nil
      end

      if attributes.key?(:'word_count')
        self.word_count = attributes[:'word_count']
      else
        self.word_count = nil
      end

      if attributes.key?(:'input')
        self.input = attributes[:'input']
      else
        self.input = nil
      end

      if attributes.key?(:'client_reference_id')
        self.client_reference_id = attributes[:'client_reference_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @object.nil?
        invalid_properties.push('invalid value for "object", object cannot be nil.')
      end

      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      if @filename.nil?
        invalid_properties.push('invalid value for "filename", filename cannot be nil.')
      end

      if @processed_at.nil?
        invalid_properties.push('invalid value for "processed_at", processed_at cannot be nil.')
      end

      if @usage.nil?
        invalid_properties.push('invalid value for "usage", usage cannot be nil.')
      end

      if @language.nil?
        invalid_properties.push('invalid value for "language", language cannot be nil.')
      end

      if @duration_seconds.nil?
        invalid_properties.push('invalid value for "duration_seconds", duration_seconds cannot be nil.')
      end

      if @text.nil?
        invalid_properties.push('invalid value for "text", text cannot be nil.')
      end

      if @dialog.nil?
        invalid_properties.push('invalid value for "dialog", dialog cannot be nil.')
      end

      if @audio_events.nil?
        invalid_properties.push('invalid value for "audio_events", audio_events cannot be nil.')
      end

      if @event_types.nil?
        invalid_properties.push('invalid value for "event_types", event_types cannot be nil.')
      end

      if @word_count.nil?
        invalid_properties.push('invalid value for "word_count", word_count cannot be nil.')
      end

      if @input.nil?
        invalid_properties.push('invalid value for "input", input cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @object.nil?
      return false if @model.nil?
      return false if @filename.nil?
      return false if @processed_at.nil?
      return false if @usage.nil?
      return false if @language.nil?
      return false if @duration_seconds.nil?
      return false if @text.nil?
      return false if @dialog.nil?
      return false if @audio_events.nil?
      return false if @event_types.nil?
      return false if @word_count.nil?
      return false if @input.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] object Value to be assigned
    def object=(object)
      if object.nil?
        fail ArgumentError, 'object cannot be nil'
      end

      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] model Value to be assigned
    def model=(model)
      if model.nil?
        fail ArgumentError, 'model cannot be nil'
      end

      @model = model
    end

    # Custom attribute writer method with validation
    # @param [Object] filename Value to be assigned
    def filename=(filename)
      if filename.nil?
        fail ArgumentError, 'filename cannot be nil'
      end

      @filename = filename
    end

    # Custom attribute writer method with validation
    # @param [Object] processed_at Value to be assigned
    def processed_at=(processed_at)
      if processed_at.nil?
        fail ArgumentError, 'processed_at cannot be nil'
      end

      @processed_at = processed_at
    end

    # Custom attribute writer method with validation
    # @param [Object] usage Value to be assigned
    def usage=(usage)
      if usage.nil?
        fail ArgumentError, 'usage cannot be nil'
      end

      @usage = usage
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] duration_seconds Value to be assigned
    def duration_seconds=(duration_seconds)
      if duration_seconds.nil?
        fail ArgumentError, 'duration_seconds cannot be nil'
      end

      @duration_seconds = duration_seconds
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if text.nil?
        fail ArgumentError, 'text cannot be nil'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] dialog Value to be assigned
    def dialog=(dialog)
      if dialog.nil?
        fail ArgumentError, 'dialog cannot be nil'
      end

      @dialog = dialog
    end

    # Custom attribute writer method with validation
    # @param [Object] audio_events Value to be assigned
    def audio_events=(audio_events)
      if audio_events.nil?
        fail ArgumentError, 'audio_events cannot be nil'
      end

      @audio_events = audio_events
    end

    # Custom attribute writer method with validation
    # @param [Object] event_types Value to be assigned
    def event_types=(event_types)
      if event_types.nil?
        fail ArgumentError, 'event_types cannot be nil'
      end

      @event_types = event_types
    end

    # Custom attribute writer method with validation
    # @param [Object] word_count Value to be assigned
    def word_count=(word_count)
      if word_count.nil?
        fail ArgumentError, 'word_count cannot be nil'
      end

      @word_count = word_count
    end

    # Custom attribute writer method with validation
    # @param [Object] input Value to be assigned
    def input=(input)
      if input.nil?
        fail ArgumentError, 'input cannot be nil'
      end

      @input = input
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object == o.object &&
          model == o.model &&
          filename == o.filename &&
          processed_at == o.processed_at &&
          usage == o.usage &&
          language == o.language &&
          language_confidence == o.language_confidence &&
          duration_seconds == o.duration_seconds &&
          text == o.text &&
          dialog == o.dialog &&
          audio_events == o.audio_events &&
          event_types == o.event_types &&
          word_count == o.word_count &&
          input == o.input &&
          client_reference_id == o.client_reference_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object, model, filename, processed_at, usage, language, language_confidence, duration_seconds, text, dialog, audio_events, event_types, word_count, input, client_reference_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
