=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class UsageByKeyItem < ApiModelBase
    # API key id
    attr_accessor :key_id

    # API key name
    attr_accessor :key_name

    # Total credits consumed by the key
    attr_accessor :total_credits

    # Number of requests
    attr_accessor :request_count

    # ISO 8601 of last use (null if never)
    attr_accessor :last_used

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'key_id' => :'key_id',
        :'key_name' => :'key_name',
        :'total_credits' => :'total_credits',
        :'request_count' => :'request_count',
        :'last_used' => :'last_used'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'key_id' => :'String',
        :'key_name' => :'String',
        :'total_credits' => :'Integer',
        :'request_count' => :'Integer',
        :'last_used' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::UsageByKeyItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::UsageByKeyItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'key_id')
        self.key_id = attributes[:'key_id']
      else
        self.key_id = nil
      end

      if attributes.key?(:'key_name')
        self.key_name = attributes[:'key_name']
      else
        self.key_name = nil
      end

      if attributes.key?(:'total_credits')
        self.total_credits = attributes[:'total_credits']
      else
        self.total_credits = nil
      end

      if attributes.key?(:'request_count')
        self.request_count = attributes[:'request_count']
      else
        self.request_count = nil
      end

      if attributes.key?(:'last_used')
        self.last_used = attributes[:'last_used']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @key_id.nil?
        invalid_properties.push('invalid value for "key_id", key_id cannot be nil.')
      end

      if @key_name.nil?
        invalid_properties.push('invalid value for "key_name", key_name cannot be nil.')
      end

      if @total_credits.nil?
        invalid_properties.push('invalid value for "total_credits", total_credits cannot be nil.')
      end

      if @request_count.nil?
        invalid_properties.push('invalid value for "request_count", request_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @key_id.nil?
      return false if @key_name.nil?
      return false if @total_credits.nil?
      return false if @request_count.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] key_id Value to be assigned
    def key_id=(key_id)
      if key_id.nil?
        fail ArgumentError, 'key_id cannot be nil'
      end

      @key_id = key_id
    end

    # Custom attribute writer method with validation
    # @param [Object] key_name Value to be assigned
    def key_name=(key_name)
      if key_name.nil?
        fail ArgumentError, 'key_name cannot be nil'
      end

      @key_name = key_name
    end

    # Custom attribute writer method with validation
    # @param [Object] total_credits Value to be assigned
    def total_credits=(total_credits)
      if total_credits.nil?
        fail ArgumentError, 'total_credits cannot be nil'
      end

      @total_credits = total_credits
    end

    # Custom attribute writer method with validation
    # @param [Object] request_count Value to be assigned
    def request_count=(request_count)
      if request_count.nil?
        fail ArgumentError, 'request_count cannot be nil'
      end

      @request_count = request_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          key_id == o.key_id &&
          key_name == o.key_name &&
          total_credits == o.total_credits &&
          request_count == o.request_count &&
          last_used == o.last_used
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [key_id, key_name, total_credits, request_count, last_used].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
