=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.48

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class WebhookEvent
    SUBSCRIPTION_CREATED = "subscription.created".freeze
    AVULSO_COMPLETED = "avulso.completed".freeze
    SUBSCRIPTION_UPGRADED = "subscription.upgraded".freeze
    SUBSCRIPTION_DOWNGRADED = "subscription.downgraded".freeze
    SUBSCRIPTION_CANCELED = "subscription.canceled".freeze
    CREDITS_LOW = "credits.low".freeze
    CREDITS_EXHAUSTED = "credits.exhausted".freeze
    SUBSCRIPTION_RENEWED = "subscription.renewed".freeze
    SUBSCRIPTION_EXPIRED = "subscription.expired".freeze
    PAYMENT_FAILED = "payment.failed".freeze

    def self.all_vars
      @all_vars ||= [SUBSCRIPTION_CREATED, AVULSO_COMPLETED, SUBSCRIPTION_UPGRADED, SUBSCRIPTION_DOWNGRADED, SUBSCRIPTION_CANCELED, CREDITS_LOW, CREDITS_EXHAUSTED, SUBSCRIPTION_RENEWED, SUBSCRIPTION_EXPIRED, PAYMENT_FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WebhookEvent.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WebhookEvent"
    end
  end
end
