=begin
#FalaAI API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.51

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class WhatsappMeta < ApiModelBase
    # Uploaded file name
    attr_accessor :file

    # chat.txt entry name inside the export
    attr_accessor :chat_txt

    # Detected format: Android | iOS
    attr_accessor :format

    # Date order used
    attr_accessor :date_format

    # Timezone informed
    attr_accessor :timezone

    # Window start (ISO)
    attr_accessor :start

    # Window end (ISO)
    attr_accessor :_end

    # Gap used to split conversations
    attr_accessor :gap_minutes

    # Minimum messages per conversation
    attr_accessor :min_messages

    # Chars per minute used to estimate duration
    attr_accessor :chars_per_minute

    # Total parsed turns
    attr_accessor :turns

    # System lines ignored
    attr_accessor :system_lines

    # Conversations before window filter
    attr_accessor :conversations_total

    # Conversations overlapping the window
    attr_accessor :conversations_in_window

    # Single-speaker conversations dropped
    attr_accessor :monologues_dropped

    # Final conversations returned
    attr_accessor :conversations_selected

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'file' => :'file',
        :'chat_txt' => :'chat_txt',
        :'format' => :'format',
        :'date_format' => :'date_format',
        :'timezone' => :'timezone',
        :'start' => :'start',
        :'_end' => :'end',
        :'gap_minutes' => :'gap_minutes',
        :'min_messages' => :'min_messages',
        :'chars_per_minute' => :'chars_per_minute',
        :'turns' => :'turns',
        :'system_lines' => :'system_lines',
        :'conversations_total' => :'conversations_total',
        :'conversations_in_window' => :'conversations_in_window',
        :'monologues_dropped' => :'monologues_dropped',
        :'conversations_selected' => :'conversations_selected'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'file' => :'String',
        :'chat_txt' => :'String',
        :'format' => :'String',
        :'date_format' => :'String',
        :'timezone' => :'String',
        :'start' => :'String',
        :'_end' => :'String',
        :'gap_minutes' => :'Float',
        :'min_messages' => :'Integer',
        :'chars_per_minute' => :'Float',
        :'turns' => :'Integer',
        :'system_lines' => :'Integer',
        :'conversations_total' => :'Integer',
        :'conversations_in_window' => :'Integer',
        :'monologues_dropped' => :'Integer',
        :'conversations_selected' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::WhatsappMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::WhatsappMeta`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'file')
        self.file = attributes[:'file']
      else
        self.file = nil
      end

      if attributes.key?(:'chat_txt')
        self.chat_txt = attributes[:'chat_txt']
      else
        self.chat_txt = nil
      end

      if attributes.key?(:'format')
        self.format = attributes[:'format']
      else
        self.format = nil
      end

      if attributes.key?(:'date_format')
        self.date_format = attributes[:'date_format']
      else
        self.date_format = nil
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = nil
      end

      if attributes.key?(:'start')
        self.start = attributes[:'start']
      else
        self.start = nil
      end

      if attributes.key?(:'_end')
        self._end = attributes[:'_end']
      else
        self._end = nil
      end

      if attributes.key?(:'gap_minutes')
        self.gap_minutes = attributes[:'gap_minutes']
      else
        self.gap_minutes = nil
      end

      if attributes.key?(:'min_messages')
        self.min_messages = attributes[:'min_messages']
      else
        self.min_messages = nil
      end

      if attributes.key?(:'chars_per_minute')
        self.chars_per_minute = attributes[:'chars_per_minute']
      else
        self.chars_per_minute = nil
      end

      if attributes.key?(:'turns')
        self.turns = attributes[:'turns']
      else
        self.turns = nil
      end

      if attributes.key?(:'system_lines')
        self.system_lines = attributes[:'system_lines']
      else
        self.system_lines = nil
      end

      if attributes.key?(:'conversations_total')
        self.conversations_total = attributes[:'conversations_total']
      else
        self.conversations_total = nil
      end

      if attributes.key?(:'conversations_in_window')
        self.conversations_in_window = attributes[:'conversations_in_window']
      else
        self.conversations_in_window = nil
      end

      if attributes.key?(:'monologues_dropped')
        self.monologues_dropped = attributes[:'monologues_dropped']
      else
        self.monologues_dropped = nil
      end

      if attributes.key?(:'conversations_selected')
        self.conversations_selected = attributes[:'conversations_selected']
      else
        self.conversations_selected = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @file.nil?
        invalid_properties.push('invalid value for "file", file cannot be nil.')
      end

      if @chat_txt.nil?
        invalid_properties.push('invalid value for "chat_txt", chat_txt cannot be nil.')
      end

      if @format.nil?
        invalid_properties.push('invalid value for "format", format cannot be nil.')
      end

      if @date_format.nil?
        invalid_properties.push('invalid value for "date_format", date_format cannot be nil.')
      end

      if @timezone.nil?
        invalid_properties.push('invalid value for "timezone", timezone cannot be nil.')
      end

      if @start.nil?
        invalid_properties.push('invalid value for "start", start cannot be nil.')
      end

      if @_end.nil?
        invalid_properties.push('invalid value for "_end", _end cannot be nil.')
      end

      if @gap_minutes.nil?
        invalid_properties.push('invalid value for "gap_minutes", gap_minutes cannot be nil.')
      end

      if @min_messages.nil?
        invalid_properties.push('invalid value for "min_messages", min_messages cannot be nil.')
      end

      if @chars_per_minute.nil?
        invalid_properties.push('invalid value for "chars_per_minute", chars_per_minute cannot be nil.')
      end

      if @turns.nil?
        invalid_properties.push('invalid value for "turns", turns cannot be nil.')
      end

      if @system_lines.nil?
        invalid_properties.push('invalid value for "system_lines", system_lines cannot be nil.')
      end

      if @conversations_total.nil?
        invalid_properties.push('invalid value for "conversations_total", conversations_total cannot be nil.')
      end

      if @conversations_in_window.nil?
        invalid_properties.push('invalid value for "conversations_in_window", conversations_in_window cannot be nil.')
      end

      if @monologues_dropped.nil?
        invalid_properties.push('invalid value for "monologues_dropped", monologues_dropped cannot be nil.')
      end

      if @conversations_selected.nil?
        invalid_properties.push('invalid value for "conversations_selected", conversations_selected cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @file.nil?
      return false if @chat_txt.nil?
      return false if @format.nil?
      return false if @date_format.nil?
      return false if @timezone.nil?
      return false if @start.nil?
      return false if @_end.nil?
      return false if @gap_minutes.nil?
      return false if @min_messages.nil?
      return false if @chars_per_minute.nil?
      return false if @turns.nil?
      return false if @system_lines.nil?
      return false if @conversations_total.nil?
      return false if @conversations_in_window.nil?
      return false if @monologues_dropped.nil?
      return false if @conversations_selected.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] file Value to be assigned
    def file=(file)
      if file.nil?
        fail ArgumentError, 'file cannot be nil'
      end

      @file = file
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_txt Value to be assigned
    def chat_txt=(chat_txt)
      if chat_txt.nil?
        fail ArgumentError, 'chat_txt cannot be nil'
      end

      @chat_txt = chat_txt
    end

    # Custom attribute writer method with validation
    # @param [Object] format Value to be assigned
    def format=(format)
      if format.nil?
        fail ArgumentError, 'format cannot be nil'
      end

      @format = format
    end

    # Custom attribute writer method with validation
    # @param [Object] date_format Value to be assigned
    def date_format=(date_format)
      if date_format.nil?
        fail ArgumentError, 'date_format cannot be nil'
      end

      @date_format = date_format
    end

    # Custom attribute writer method with validation
    # @param [Object] timezone Value to be assigned
    def timezone=(timezone)
      if timezone.nil?
        fail ArgumentError, 'timezone cannot be nil'
      end

      @timezone = timezone
    end

    # Custom attribute writer method with validation
    # @param [Object] start Value to be assigned
    def start=(start)
      if start.nil?
        fail ArgumentError, 'start cannot be nil'
      end

      @start = start
    end

    # Custom attribute writer method with validation
    # @param [Object] _end Value to be assigned
    def _end=(_end)
      if _end.nil?
        fail ArgumentError, '_end cannot be nil'
      end

      @_end = _end
    end

    # Custom attribute writer method with validation
    # @param [Object] gap_minutes Value to be assigned
    def gap_minutes=(gap_minutes)
      if gap_minutes.nil?
        fail ArgumentError, 'gap_minutes cannot be nil'
      end

      @gap_minutes = gap_minutes
    end

    # Custom attribute writer method with validation
    # @param [Object] min_messages Value to be assigned
    def min_messages=(min_messages)
      if min_messages.nil?
        fail ArgumentError, 'min_messages cannot be nil'
      end

      @min_messages = min_messages
    end

    # Custom attribute writer method with validation
    # @param [Object] chars_per_minute Value to be assigned
    def chars_per_minute=(chars_per_minute)
      if chars_per_minute.nil?
        fail ArgumentError, 'chars_per_minute cannot be nil'
      end

      @chars_per_minute = chars_per_minute
    end

    # Custom attribute writer method with validation
    # @param [Object] turns Value to be assigned
    def turns=(turns)
      if turns.nil?
        fail ArgumentError, 'turns cannot be nil'
      end

      @turns = turns
    end

    # Custom attribute writer method with validation
    # @param [Object] system_lines Value to be assigned
    def system_lines=(system_lines)
      if system_lines.nil?
        fail ArgumentError, 'system_lines cannot be nil'
      end

      @system_lines = system_lines
    end

    # Custom attribute writer method with validation
    # @param [Object] conversations_total Value to be assigned
    def conversations_total=(conversations_total)
      if conversations_total.nil?
        fail ArgumentError, 'conversations_total cannot be nil'
      end

      @conversations_total = conversations_total
    end

    # Custom attribute writer method with validation
    # @param [Object] conversations_in_window Value to be assigned
    def conversations_in_window=(conversations_in_window)
      if conversations_in_window.nil?
        fail ArgumentError, 'conversations_in_window cannot be nil'
      end

      @conversations_in_window = conversations_in_window
    end

    # Custom attribute writer method with validation
    # @param [Object] monologues_dropped Value to be assigned
    def monologues_dropped=(monologues_dropped)
      if monologues_dropped.nil?
        fail ArgumentError, 'monologues_dropped cannot be nil'
      end

      @monologues_dropped = monologues_dropped
    end

    # Custom attribute writer method with validation
    # @param [Object] conversations_selected Value to be assigned
    def conversations_selected=(conversations_selected)
      if conversations_selected.nil?
        fail ArgumentError, 'conversations_selected cannot be nil'
      end

      @conversations_selected = conversations_selected
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          file == o.file &&
          chat_txt == o.chat_txt &&
          format == o.format &&
          date_format == o.date_format &&
          timezone == o.timezone &&
          start == o.start &&
          _end == o._end &&
          gap_minutes == o.gap_minutes &&
          min_messages == o.min_messages &&
          chars_per_minute == o.chars_per_minute &&
          turns == o.turns &&
          system_lines == o.system_lines &&
          conversations_total == o.conversations_total &&
          conversations_in_window == o.conversations_in_window &&
          monologues_dropped == o.monologues_dropped &&
          conversations_selected == o.conversations_selected
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [file, chat_txt, format, date_format, timezone, start, _end, gap_minutes, min_messages, chars_per_minute, turns, system_lines, conversations_total, conversations_in_window, monologues_dropped, conversations_selected].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
