=begin
#FalaAI API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.51

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module FalaAI
  class WhatsappConversation < ApiModelBase
    # Conversation identifier in the batch
    attr_accessor :conversation_id

    # Real start (wall-clock, ISO)
    attr_accessor :first_at

    # Real end (wall-clock, ISO)
    attr_accessor :last_at

    # (last - first) + last turn duration
    attr_accessor :duration_seconds

    # Speakers of THIS conversation (dynamic)
    attr_accessor :speakers

    # Lines 'Speaker N: [HH:MM:SS.mmm - HH:MM:SS.mmm] text' (real offset)
    attr_accessor :dialog

    # Number of messages
    attr_accessor :message_count

    # Total characters of the conversation
    attr_accessor :characters

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'conversation_id' => :'conversation_id',
        :'first_at' => :'first_at',
        :'last_at' => :'last_at',
        :'duration_seconds' => :'duration_seconds',
        :'speakers' => :'speakers',
        :'dialog' => :'dialog',
        :'message_count' => :'message_count',
        :'characters' => :'characters'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'conversation_id' => :'String',
        :'first_at' => :'String',
        :'last_at' => :'String',
        :'duration_seconds' => :'Float',
        :'speakers' => :'Array<WhatsappSpeaker>',
        :'dialog' => :'String',
        :'message_count' => :'Integer',
        :'characters' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FalaAI::WhatsappConversation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FalaAI::WhatsappConversation`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'conversation_id')
        self.conversation_id = attributes[:'conversation_id']
      else
        self.conversation_id = nil
      end

      if attributes.key?(:'first_at')
        self.first_at = attributes[:'first_at']
      else
        self.first_at = nil
      end

      if attributes.key?(:'last_at')
        self.last_at = attributes[:'last_at']
      else
        self.last_at = nil
      end

      if attributes.key?(:'duration_seconds')
        self.duration_seconds = attributes[:'duration_seconds']
      else
        self.duration_seconds = nil
      end

      if attributes.key?(:'speakers')
        if (value = attributes[:'speakers']).is_a?(Array)
          self.speakers = value
        end
      else
        self.speakers = nil
      end

      if attributes.key?(:'dialog')
        self.dialog = attributes[:'dialog']
      else
        self.dialog = nil
      end

      if attributes.key?(:'message_count')
        self.message_count = attributes[:'message_count']
      else
        self.message_count = nil
      end

      if attributes.key?(:'characters')
        self.characters = attributes[:'characters']
      else
        self.characters = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @conversation_id.nil?
        invalid_properties.push('invalid value for "conversation_id", conversation_id cannot be nil.')
      end

      if @first_at.nil?
        invalid_properties.push('invalid value for "first_at", first_at cannot be nil.')
      end

      if @last_at.nil?
        invalid_properties.push('invalid value for "last_at", last_at cannot be nil.')
      end

      if @duration_seconds.nil?
        invalid_properties.push('invalid value for "duration_seconds", duration_seconds cannot be nil.')
      end

      if @speakers.nil?
        invalid_properties.push('invalid value for "speakers", speakers cannot be nil.')
      end

      if @dialog.nil?
        invalid_properties.push('invalid value for "dialog", dialog cannot be nil.')
      end

      if @message_count.nil?
        invalid_properties.push('invalid value for "message_count", message_count cannot be nil.')
      end

      if @characters.nil?
        invalid_properties.push('invalid value for "characters", characters cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @conversation_id.nil?
      return false if @first_at.nil?
      return false if @last_at.nil?
      return false if @duration_seconds.nil?
      return false if @speakers.nil?
      return false if @dialog.nil?
      return false if @message_count.nil?
      return false if @characters.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] conversation_id Value to be assigned
    def conversation_id=(conversation_id)
      if conversation_id.nil?
        fail ArgumentError, 'conversation_id cannot be nil'
      end

      @conversation_id = conversation_id
    end

    # Custom attribute writer method with validation
    # @param [Object] first_at Value to be assigned
    def first_at=(first_at)
      if first_at.nil?
        fail ArgumentError, 'first_at cannot be nil'
      end

      @first_at = first_at
    end

    # Custom attribute writer method with validation
    # @param [Object] last_at Value to be assigned
    def last_at=(last_at)
      if last_at.nil?
        fail ArgumentError, 'last_at cannot be nil'
      end

      @last_at = last_at
    end

    # Custom attribute writer method with validation
    # @param [Object] duration_seconds Value to be assigned
    def duration_seconds=(duration_seconds)
      if duration_seconds.nil?
        fail ArgumentError, 'duration_seconds cannot be nil'
      end

      @duration_seconds = duration_seconds
    end

    # Custom attribute writer method with validation
    # @param [Object] speakers Value to be assigned
    def speakers=(speakers)
      if speakers.nil?
        fail ArgumentError, 'speakers cannot be nil'
      end

      @speakers = speakers
    end

    # Custom attribute writer method with validation
    # @param [Object] dialog Value to be assigned
    def dialog=(dialog)
      if dialog.nil?
        fail ArgumentError, 'dialog cannot be nil'
      end

      @dialog = dialog
    end

    # Custom attribute writer method with validation
    # @param [Object] message_count Value to be assigned
    def message_count=(message_count)
      if message_count.nil?
        fail ArgumentError, 'message_count cannot be nil'
      end

      @message_count = message_count
    end

    # Custom attribute writer method with validation
    # @param [Object] characters Value to be assigned
    def characters=(characters)
      if characters.nil?
        fail ArgumentError, 'characters cannot be nil'
      end

      @characters = characters
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          conversation_id == o.conversation_id &&
          first_at == o.first_at &&
          last_at == o.last_at &&
          duration_seconds == o.duration_seconds &&
          speakers == o.speakers &&
          dialog == o.dialog &&
          message_count == o.message_count &&
          characters == o.characters
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [conversation_id, first_at, last_at, duration_seconds, speakers, dialog, message_count, characters].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
