=begin
#FalaAI API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.49

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

# Common files
require 'falaai-api/api_client'
require 'falaai-api/api_error'
require 'falaai-api/api_model_base'
require 'falaai-api/version'
require 'falaai-api/configuration'

# Models
require 'falaai-api/models/audio_event'
require 'falaai-api/models/audio_input_meta'
require 'falaai-api/models/create_email_alert_request'
require 'falaai-api/models/create_webhook_request'
require 'falaai-api/models/diagnostic_analysis_map'
require 'falaai-api/models/diagnostic_audio_event'
require 'falaai-api/models/diagnostic_categorical_analysis'
require 'falaai-api/models/diagnostic_participant'
require 'falaai-api/models/diagnostic_request'
require 'falaai-api/models/diagnostic_response'
require 'falaai-api/models/diagnostic_text_analysis'
require 'falaai-api/models/diagnostic_usage'
require 'falaai-api/models/email_alert_item'
require 'falaai-api/models/email_alert_list_response'
require 'falaai-api/models/email_alert_message_response'
require 'falaai-api/models/email_event'
require 'falaai-api/models/http_validation_error'
require 'falaai-api/models/health_response'
require 'falaai-api/models/location_inner'
require 'falaai-api/models/message_response'
require 'falaai-api/models/participant'
require 'falaai-api/models/participant_diagnostic'
require 'falaai-api/models/risk_audit_analysis_v2'
require 'falaai-api/models/risk_audit_applied_action_v2'
require 'falaai-api/models/risk_audit_audio_event_model_v2'
require 'falaai-api/models/risk_audit_audit_decisions_v2'
require 'falaai-api/models/risk_audit_conversation_scores_v2'
require 'falaai-api/models/risk_audit_detection_item_v2'
require 'falaai-api/models/risk_audit_detections_v2'
require 'falaai-api/models/risk_audit_indexer_v2'
require 'falaai-api/models/risk_audit_meta_v2'
require 'falaai-api/models/risk_audit_participant_v2'
require 'falaai-api/models/risk_audit_participants_v2'
require 'falaai-api/models/risk_audit_request'
require 'falaai-api/models/risk_audit_scores_v2'
require 'falaai-api/models/risk_audit_scoring_explanation_v2'
require 'falaai-api/models/risk_audit_summary_v2'
require 'falaai-api/models/risk_audit_timeline_v2'
require 'falaai-api/models/risk_audit_usage_v2'
require 'falaai-api/models/risk_audit_v2'
require 'falaai-api/models/risk_audit_v2_response'
require 'falaai-api/models/risk_audit_verdict_v2'
require 'falaai-api/models/transcription_response'
require 'falaai-api/models/transcription_usage'
require 'falaai-api/models/update_email_alert_request'
require 'falaai-api/models/update_webhook_request'
require 'falaai-api/models/usage_by_key_item'
require 'falaai-api/models/usage_log_item'
require 'falaai-api/models/usage_log_response'
require 'falaai-api/models/validation_error'
require 'falaai-api/models/version_response'
require 'falaai-api/models/webhook_event'
require 'falaai-api/models/webhook_item'
require 'falaai-api/models/webhook_list_response'

# APIs
require 'falaai-api/api/analysis_api'
require 'falaai-api/api/email_alerts_api'
require 'falaai-api/api/health_api'
require 'falaai-api/api/speech_api'
require 'falaai-api/api/usage_api'
require 'falaai-api/api/version_api'
require 'falaai-api/api/webhooks_api'

module FalaAI
  class << self
    # Customize default settings for the SDK using block.
    #   FalaAI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
