=begin
#FalaAI API

#Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)

The version of the OpenAPI document: 1.21.47

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

# Common files
require 'falaai-api/api_client'
require 'falaai-api/api_error'
require 'falaai-api/api_model_base'
require 'falaai-api/version'
require 'falaai-api/configuration'

# Models
require 'falaai-api/models/audio_event'
require 'falaai-api/models/audio_input_meta'
require 'falaai-api/models/auditoria_risco_analysis_v2'
require 'falaai-api/models/auditoria_risco_applied_action_v2'
require 'falaai-api/models/auditoria_risco_audio_event_model_v2'
require 'falaai-api/models/auditoria_risco_audit_decisions_v2'
require 'falaai-api/models/auditoria_risco_conversation_scores_v2'
require 'falaai-api/models/auditoria_risco_detection_item_v2'
require 'falaai-api/models/auditoria_risco_detections_v2'
require 'falaai-api/models/auditoria_risco_indexer_v2'
require 'falaai-api/models/auditoria_risco_meta_v2'
require 'falaai-api/models/auditoria_risco_participant_v2'
require 'falaai-api/models/auditoria_risco_participants_v2'
require 'falaai-api/models/auditoria_risco_request'
require 'falaai-api/models/auditoria_risco_scores_v2'
require 'falaai-api/models/auditoria_risco_scoring_explanation_v2'
require 'falaai-api/models/auditoria_risco_summary_v2'
require 'falaai-api/models/auditoria_risco_timeline_v2'
require 'falaai-api/models/auditoria_risco_usage_v2'
require 'falaai-api/models/auditoria_risco_v2'
require 'falaai-api/models/auditoria_risco_v2_response'
require 'falaai-api/models/auditoria_risco_verdict_v2'
require 'falaai-api/models/create_email_alert_request'
require 'falaai-api/models/create_webhook_request'
require 'falaai-api/models/diagnostic_analysis_map'
require 'falaai-api/models/diagnostic_audio_event'
require 'falaai-api/models/diagnostic_categorical_analysis'
require 'falaai-api/models/diagnostic_request'
require 'falaai-api/models/diagnostic_response'
require 'falaai-api/models/diagnostic_text_analysis'
require 'falaai-api/models/diagnostic_usage'
require 'falaai-api/models/email_alert_item'
require 'falaai-api/models/email_alert_list_response'
require 'falaai-api/models/email_alert_message_response'
require 'falaai-api/models/email_event'
require 'falaai-api/models/http_validation_error'
require 'falaai-api/models/health_response'
require 'falaai-api/models/location_inner'
require 'falaai-api/models/message_response'
require 'falaai-api/models/participant'
require 'falaai-api/models/participant_diagnostic'
require 'falaai-api/models/transcription_response'
require 'falaai-api/models/transcription_usage'
require 'falaai-api/models/update_email_alert_request'
require 'falaai-api/models/update_webhook_request'
require 'falaai-api/models/usage_by_key_item'
require 'falaai-api/models/usage_log_item'
require 'falaai-api/models/usage_log_response'
require 'falaai-api/models/validation_error'
require 'falaai-api/models/version_response'
require 'falaai-api/models/webhook_event'
require 'falaai-api/models/webhook_item'
require 'falaai-api/models/webhook_list_response'

# APIs
require 'falaai-api/api/analysis_api'
require 'falaai-api/api/email_alerts_api'
require 'falaai-api/api/health_api'
require 'falaai-api/api/speech_api'
require 'falaai-api/api/usage_api'
require 'falaai-api/api/version_api'
require 'falaai-api/api/webhooks_api'

module FalaAI
  class << self
    # Customize default settings for the SDK using block.
    #   FalaAI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
