=begin
#FalaAI API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.51

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

module FalaAI
  VERSION = '1.21.51'
end
